### ISSUE TITLE
Unable to access api's using basic auth module

### ISSUE THREAD

**Issue by sw-enthusiast** [cbornet/generator-jhipster-basic-auth#3]
Hi Christophe 

I have generated this module in Jhipster 3.12.2 for micro services application. I am trying to access my end points from postman with admin, admin username and password and I am getting 401 unauthorized. 

My requirement is to use basic auth for the api's that are being exposed to the clients. 
sample endpoint: 

> http://localhost:8081/api_basic/items

Error message:
```
{
  "timestamp": "2017-01-03T16:47:24.478+0000",
  "status": 401,
  "error": "Unauthorized",
  "message": "Bad credentials",
  "path": "/api_basic/items"
}
```
When I tried this endpoint 

> http://localhost:8080/api_basic/items
I get 
```
{
  "timestamp": "2017-01-03T16:54:01.050+0000",
  "status": 404,
  "error": "Not Found",
  "message": "Not Found",
  "path": "/api_basic/items"
}
```

Do I have to do any additional configurations after generating the module? 

Thanks!

**Comment by cbornet** [comment]
Can you post your yo-rc.json ?

**Comment by sw-enthusiast** [comment]
When I generate the module it did not add anything to the the yo-rc.json file but it added entries to the jhi-hooks.json file

 jhi-hooks.json
```
[
    {
        "name": "Entity Audit generator",
        "npmPackageName": "generator-jhipster-entity-audit",
        "description": "Add support for entity audit and audit log page",
        "hookFor": "entity",
        "hookType": "post",
        "generatorCallback": "jhipster-entity-audit:entity"
    },
    {
        "name": "Basic Auth generator",
        "npmPackageName": "generator-jhipster-basic-auth",
        "description": "Adds stateless basic authentication support",
        "hookFor": "entity",
        "hookType": "post",
        "generatorCallback": "jhipster-basic-auth:entity"
    }
]
```

yo-rc.json
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "warehouseServices",
    "packageName": "com.company.ws",
    "packageFolder": "com/company/ws",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xyz",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "es"
    ]
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}
```

**Comment by cbornet** [comment]
Thx. I'll have a look asap.

**Comment by cbornet** [comment]
So I'm afraid this module doesn't work with JWT authenticated micro-services.
The reason is that the user management is done by the gateway and the micro-service only validates a generated JWT but doesn't communicate at all with the user domain.
So you can't put basic auth directly on the micro-service.
The gateway can get the user details but then it would need to generate and attach a valid JWT for the micro-service (this would be a little curious architecture and completely out of scope of this really simple module)

So I'll document that this module is for monolith only (it was created before micro-services even existed). 

Sorry about that :disappointed: ... Can I ask why you don't want to use JWT auth on your clients ?

**Comment by sw-enthusiast** [comment]
Most of our client applications are hosted outside the network, we want to integrate Ldap authentication down the road. 

I can convince my lead that we use the jwt. My questions are: Should I just share the token with my client? I was confused when the jhipster documentation says the jwt token is valid only for 24 hrs. How does this really work?

Thank you!

**Comment by cbornet** [comment]
If you want to use LDAP, you might consider [using UAA](https://jhipster.github.io/using-uaa/) as auth system as it seems to have [support for LDAP](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-LDAP.md).

With simple JWT (not UAA), the JWT token is sent as response (in body and headers) to the request to `/authenticate` end-point when you pass it correct credentials (eg [angular code](https://github.com/jhipster/jhipster-sample-app-gateway/blob/ee18d80481ab2f5203a6003c9fce1be6d4b5806b/src/main/webapp/app/services/auth/auth.jwt.service.js#L25)). 
Indeed, it has an expiry time for security reason (this is configurable in your application.yml) so you need to call the authorize endpoint again with the user/password info if you get a 401 error.

**Comment by cbornet** [comment]
And the token is a derivative of the user/password of your client (your don't share the secret key that has signed the token) so it's safe for the client to see it.

**Comment by sw-enthusiast** [comment]
We are going to go with the default JWT auth for our prototype. Thanks Christophe for your quick response.

**Comment by cbornet** [comment]
README updated (https://github.com/cbornet/generator-jhipster-basic-auth/commit/fa00bf2139ff34110cab33057dfe684b4967acf7)
